language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed but can no longer be installed with
# sudo apt-get.
addons:
    apt:
        packages:
            - libatlas-dev
            - liblapack-dev
            - gfortran
            - graphviz
            - texlive-latex-extra
            - dvipng

python:
    - 2.7
    - 3.5
    - 3.6

# Configure the build environment. Global varibles are defined for all configurations.
env:
    global:
        - COLUMNS=240
        - NUMPY_VERSION='stable'
        - ASTROPY_VERSION='stable'
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - PIP_DEPENDENCIES='git+https://github.com/sunpy/sunpy-sphinx-theme.git'
        - CONDA_CHANNELS='conda-forge'
        - CONDA_DEPENDENCIES='sunpy'
        - EVENT_TYPE='pull_request push'

    matrix:
        - SETUP_CMD='egg_info'

matrix:
    include:
         # We order the jobs, so the longest running tests are in the top
         # four positions of the matrix
         - os: osx
           language: generic
           env: PYTHON_VERSION=3.6

         - python: 2.7
           env: SETUP_CMD='test'

         - python: 3.6
           env: SETUP_CMD='build_docs -w'
                EVENT_TYPE='push pull_request cron'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == *coverage* ]]; then coveralls --rcfile='./pysst/tests/coveragerc'; fi
